### ISSUE TITLE
'Magma Blocks Mixin' cause game to crash on opening

### ISSUE THREAD

**Issue by SpinWin** [03-JS/Extra-Enchantments-and-Curses#11]
https://gist.github.com/SpinWin/fb9544880026b6ac4b0bb847f154d115

**Comment by EvilCh33z** [comment]
I, too, get a magma block related error thrown and I only see two mods mentioned. Made a post on the "[Quad](https://github.com/LieOnLion/Quad)" [Issue Tracker](https://github.com/LieOnLion/Quad/issues/6#issue-2290668069), then realized I saw extraenchantments noted in the error as well...

ALso worth mentioning that I dont have this error thrown by either of these two mods until I update the 'Quad' Mod to its 1.2.0 or later versions so I am mostly posting this here for the off chance that its a recurring interaction.
Any help would be appreciated.

TIA!

[22:53:46] [pool-5-thread-1/FATAL]: Mixin apply failed quad.mixins.json:MagmaBlockMixin -> net.minecraft.world.level.block.MagmaBlock: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException @at("INVOKE") on net/minecraft/world/level/block/MagmaBlock::applyTagProtectsFromBurns with priority 1000 cannot inject into net/minecraft/world/level/block/MagmaBlock::m_141947_(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/entity/Entity;)V merged by net.js03.extraenchantments.mixin.MagmaBlockMixin with priority 1000 [PREINJECT Applicator Phase -> quad.mixins.json:MagmaBlockMixin -> Prepare Injections -> -> wrapOperation$zid001$applyTagProtectsFromBurns(Lnet/minecraft/world/entity/LivingEntity;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Z -> Prepare]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: @at("INVOKE") on net/minecraft/world/level/block/MagmaBlock::applyTagProtectsFromBurns with priority 1000 cannot inject into net/minecraft/world/level/block/MagmaBlock::m_141947_(Lnet/minecraft/world/level/Level;Lnet/minecraft/core/BlockPos;Lnet/minecraft/world/level/block/state/BlockState;Lnet/minecraft/world/entity/Entity;)V merged by net.js03.extraenchantments.mixin.MagmaBlockMixin with priority 1000 [PREINJECT Applicator Phase -> quad.mixins.json:MagmaBlockMixin -> Prepare Injections -> -> wrapOperation$zid001$applyTagProtectsFromBurns(Lnet/minecraft/world/entity/LivingEntity;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Z -> Prepare]
at org.spongepowered.asm.mixin.injection.code.Injector.findTargetNodes(Injector.java:305) ~[mixin-0.8.5.jar!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.injection.code.Injector.find(Injector.java:240) ~[mixin-0.8.5.jar!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.prepare(InjectionInfo.java:421) ~[mixin-0.8.5.jar!/:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at com.llamalad7.mixinextras.injector.wrapoperation.WrapOperationInjectionInfo.prepare(WrapOperationInjectionInfo.java:38) ~[MixinExtras-0.3.5.jar%2337!/:?]
at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1319) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1042) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:393) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4]
at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:142) ~[modlauncher-10.1.2.jar:10.1.2]
at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:91) ~[modlauncher-10.1.2.jar:?]
at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:107) ~[modlauncher-10.1.2.jar:?]
at cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:44) ~[modlauncher-10.1.2.jar:?]
at net.minecraftforge.securemodules.SecureModuleClassLoader.readerToClass(SecureModuleClassLoader.java:473) ~[securemodules-2.2.10.jar!/:?]
at net.minecraftforge.securemodules.SecureModuleClassLoader.findClass(SecureModuleClassLoader.java:399) ~[securemodules-2.2.10.jar!/:?]
at net.minecraftforge.securemodules.SecureModuleClassLoader.loadClass(SecureModuleClassLoader.java:415) ~[securemodules-2.2.10.jar!/:?]
at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
at net.minecraft.world.level.block.FireBlock.m_53484_(FireBlock.java:307) ~[forge-1.20.4-49.0.50-client.jar!/:?]
at net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:46) ~[forge-1.20.4-49.0.50-client.jar!/:?]
at net.minecraft.client.main.Main.lambda$main$0(Main.java:156) ~[forge-1.20.4-49.0.50-client.jar!/:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

[latest.log](https://github.com/LieOnLion/Quad/files/15281668/latest.log)

**Comment by lieonlion** [comment]
Fixed on my end, will be added in the next Quad update. but for it to have full Quad compat a datapack will need to be added and the Hellwalker enchantment added to the tag "quad:protects_from/burns", which will then apply it to campfires too.

**Comment by lieonlion** [comment]
I will add it to my planned mod support - https://lieonlion.github.io/quad-docs/quad-extra

**Comment by lieonlion** [comment]
I have released the new version, if you ever use Hellwalker, make sure to add it to the tag
